In [1]:
using LinearAlgebra
using Plots
using LaTeXStrings


In [78]:
"\$(\\alpha)$"

LoadError: syntax: invalid interpolation syntax: "$""

In [2]:
U = [sqrt(2) 0; 0 sqrt(2)]

2×2 Array{Float64,2}:
 1.41421  0.0    
 0.0      1.41421

In [3]:
S = [1 0; 0 0]

2×2 Array{Int64,2}:
 1  0
 0  0

In [4]:
V = [sqrt(2)/2 sqrt(2)/2; sqrt(2)/2 -sqrt(2)/2]

2×2 Array{Float64,2}:
 0.707107   0.707107
 0.707107  -0.707107

In [5]:
U*S*V

2×2 Array{Float64,2}:
 1.0  1.0
 0.0  0.0

In [6]:
A = [1 1; 1 1]

2×2 Array{Int64,2}:
 1  1
 1  1

In [7]:
svd(A)

SVD{Float64,Float64,Array{Float64,2}}([-0.7071067811865472 -0.7071067811865475; -0.7071067811865475 0.7071067811865475], [2.0, 0.0], [-0.7071067811865476 -0.7071067811865475; -0.7071067811865475 0.7071067811865476])

In [8]:
angles = LinRange(0,2π, 20000)

20000-element LinRange{Float64}:
 0.0,0.000314175,0.00062835,0.000942525,…,6.28224,6.28256,6.28287,6.28319

In [9]:
unitVectors = []

for angle in angles
    append!(unitVectors, [ [cos(angle), sin(angle) ] ])
end

Compute Matrix Norm

Input:  matrix A, unitVectors
Output: ||A||, x st ||Ax|| = ||A|| 

In [10]:
function matrixNorm(A)
    
    unitVectors = []

    for angle in angles
        append!(unitVectors, [ [cos(angle), sin(angle) ] ])
    end
    
    normA = 0
    v = [0,0]
    
    
    for vector in unitVectors
        product = A*vector
        length = norm(product)
        if length>normA
            normA = length
            v = vector
        end
    end
    
    return [normA, v]
    
end
            
            
    

matrixNorm (generic function with 1 method)

In [122]:
A = [-2 1; 4 3]

2×2 Array{Int64,2}:
 -2  1
  4  3

In [123]:
result = matrixNorm(A)

2-element Array{Any,1}:
 5.116672736008657                        
  [0.8506497855507007, 0.5257327670428646]

In [13]:
result[2][1]

0.8506497855507007

In [63]:
L"\alpha \cdot \mathrm{ test}"

L"$\alpha \cdot \mathrm{ test}$"

In [83]:
"$(\Omega_d)^2$"

LoadError: syntax: "\" is not a unary operator

In [80]:



perp = [1,0]

perp = [1,-(A*result[2])[1]/(A*result[2])[2]]
perp = perp./norm(perp)*1.95



plot( [(A*x)[1] for x in unitVectors], [(A*x)[2] for x in unitVectors], aspect_ratio=1, title= ,label="unit ball", bg = false)
plot!( [0, (A*result[2])[1]], [0, (A*result[2])[2]]  , label = "\alpha" )
plot!( [0, perp[1]], [0, perp[2]], label = L"v_2")


LoadError: syntax: invalid character "“" near column 96

L"test $test$"

(a,b)  (x,y)

(ax+by) = 0

x = 1

a+by = 0

y = -a/b




In [22]:
"test"+"string"

MethodError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529

In [17]:
v = [1;-3/8]

2-element Array{Float64,1}:
  1.0  
 -0.375

In [18]:
v=v./norm(v)

2-element Array{Float64,1}:
  0.9363291775690445
 -0.3511234415883917

In [19]:
u⋅v

0.0

LoadError: syntax: unexpected "end"

In [100]:
gramSm

-2

In [102]:
t = [1;2]
norm(t)

2.23606797749979

In [103]:
sqrt(1+4)

2.23606797749979

In [97]:
zeros(2,4)

2×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [120]:
for i in 1:0
    print(i)
end

In [113]:
function f(x)
    return(2*x)
end

f (generic function with 1 method)

In [114]:
f(2)

4

In [229]:
function gramSchmidt(A)
    m = size(A)[1]; n = size(A)[2]
    r = zeros(n,n); q = zeros(m,n)
    
    for j in 1:n
        
        v = A[:,j]
        
        for i in 1:(j-1)
            r[i,j]=q[:,i]⋅A[:,j]
            v = v - r[i,j].*q[:,i]
        end
        
        r[j,j] = norm(v)
        q[:,j] = v./r[j,j]
    end
    
    return[q,r]
    
end

            

gramSchmidt (generic function with 1 method)

In [230]:
A = [12 -51 4; 6 167 -68; -4 24 -41]

res = gramSchmidt(A)

2-element Array{Array{Float64,2},1}:
 [0.8571428571428571 -0.3942857142857143 -0.33142857142857146; 0.42857142857142855 0.9028571428571428 0.03428571428571416; -0.2857142857142857 0.17142857142857143 -0.9428571428571428]
 [14.0 20.999999999999996 -14.000000000000002; 0.0 175.0 -70.0; 0.0 0.0 35.0]                                                                                                          

In [231]:
res[1][:,1]⋅res[1][:,2]

-2.0816681711721685e-17

In [226]:
-69/175

-0.3942857142857143

In [189]:
[-0.316228 -0.948683; -0.948683 0.316228]*[-3.16228 -4.42719; 0 -0.632456]

2×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0

In [219]:
Rational(.5)

1//2